/** ESM, declaration and source-map generation for one source module. */
import { GnehError, type Metadata, type PassageIR, type Span } from '@gneh/core';
import { offsetToPosition } from '@gneh/source';
import { emitExpression, expressionKey, parseModule, visitExpressions } from '@gneh/expression';

function typeFor(p: PassageIR): string {
  const params = Array.isArray(p.metadata.params) ? p.metadata.params : [];
  const types =
    p.metadata.paramTypes && typeof p.metadata.paramTypes === 'object' && !Array.isArray(p.metadata.paramTypes)
      ? (p.metadata.paramTypes as Metadata)
      : {};
  const optional = Array.isArray(p.metadata.optionalParams) ? p.metadata.optionalParams : [];
  return `{ ${params.map((name) => `${JSON.stringify(String(name))}${optional.includes(name) ? '?' : ''}: ${typeof types[String(name)] === 'string' ? types[String(name)] : 'unknown'}`).join('; ')} }`;
}

const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

function vlq(value: number): string {
  let x = value < 0 ? (-value << 1) | 1 : value << 1;
  let out = '';
  do {
    let d = x & 31;
    x >>>= 5;
    if (x) d |= 32;
    out += chars[d];
  } while (x);
  return out;
}

export interface ModuleOutput {
  code: string;
  declarations: string;
  map: Record<string, unknown>;
}

/** A file is one ESM namespace; passage ids live in the typed `fragments` export. */
export function generateModule(
  passages: PassageIR[],
  source = '',
  file = 'story.inkdown',
  options: {
    namespace?: string;
  } = {},
): ModuleOutput {
  if (!passages.length) throw new GnehError('MODULE_EMPTY', 'No passages to compile.');
  const modules = passages.filter((p) => p.module.trim());
  if (modules.length > 1)
    throw new GnehError(
      'MODULE_BOUNDARY',
      'Use at most one @module block per source file; its bindings are shared by all passages.',
    );
  const imports = [...new Set(passages.flatMap((p) => p.imports))];
  if (
    imports.some(
      (x) => ['fragments', 'metadata', '__gneh', '__ops', '__bindings'].includes(x) || /^__(?:ir|ev|f)\d+$/.test(x),
    )
  )
    throw new GnehError('MODULE_RESERVED', 'fragments and metadata are compiler-owned export names.');
  const code: string[] = [
    '// Generated by gneh 0.1.0. Source dialect does not affect the Fragment ABI.',
    'import { defineIRFragment as __gneh } from "@gneh/runtime";',
    'import { ops as __ops } from "@gneh/core";',
    modules[0]?.module ?? '',
  ];
  const mapping: {
    line: number;
    span: Span;
  }[] = [];
  const moduleInfo = parseModule(modules[0]?.module ?? '');
  if (moduleInfo.exports.some((name) => ['fragments', 'metadata'].includes(name) || !/^[$A-Z_a-z][$\w]*$/.test(name)))
    throw new GnehError('MODULE_RESERVED', 'fragments and metadata are compiler-owned exports.');
  if (imports.some((name) => passages.some((p) => p.id === name)))
    throw new GnehError(
      'MODULE_SHADOW',
      'A local passage id cannot shadow an ESM binding. Rename the import alias or passage id.',
    );
  const bindings = '__bindings';
  code.push(
    `const __bindings = {${imports.map((name) => `get ${JSON.stringify(name)}(){ return ${name}; }`).join(',')}};`,
  );
  for (let i = 0; i < passages.length; i++) {
    const p = passages[i];
    code.push(
      `const __ir${i} = ${JSON.stringify({ ...p, id: options.namespace ? options.namespace + '#' + p.id : p.id, module: '' })};`,
    );
    code.push(`const __ev${i} = {};`);
    const seen = new Set<string>();
    visitExpressions(p.body, (e) => {
      const key = expressionKey(e);
      if (seen.has(key)) return;
      seen.add(key);
      const line = code.join('\n').split('\n').length;
      mapping.push({ line, span: e.span });
      code.push(`__ev${i}[${JSON.stringify(key)}] = (c,s) => { const ops = __ops; return ${emitExpression(e.ast)}; };`);
    });
    code.push(`const __f${i} = __gneh(__ir${i}, {bindings:${bindings},evaluators:__ev${i}});`);
  }
  code.push(
    `export const fragments = Object.freeze({${passages.map((p, i) => `${JSON.stringify(p.id)}:__f${i}`).join(',')}});`,
  );
  code.push('Object.assign(__bindings, fragments);');
  code.push(
    `export const metadata = Object.freeze(${JSON.stringify(Object.fromEntries(passages.map((p) => [p.id, p.metadata])))});`,
  );
  code.push('export default __f0;');
  const generated = code.join('\n') + '\n';
  const mapLines = generated.split('\n').map(() => '');
  let previousLine = 0,
    previousColumn = 0;
  for (const m of mapping) {
    const pos = offsetToPosition(source, m.span.start);
    mapLines[m.line] = vlq(0) + vlq(0) + vlq(pos.line - previousLine) + vlq(pos.character - previousColumn);
    previousLine = pos.line;
    previousColumn = pos.character;
  }
  const declarations =
    [
      'import type { Fragment, Metadata } from "@gneh/core";',
      ...moduleInfo.exports.map((name) =>
        moduleInfo.functions.includes(name)
          ? `export declare function ${name}(...args: unknown[]): unknown;`
          : `export declare const ${name}: unknown;`,
      ),
      `export declare const fragments: {${passages.map((p) => `readonly ${JSON.stringify(p.id)}: Fragment<${typeFor(p)}>`).join(';')}};`,
      'export declare const metadata: Readonly<Record<string,Metadata>>;',
      `declare const primary: Fragment<${typeFor(passages[0])}>;`,
      'export default primary;',
    ].join('\n') + '\n';
  return {
    code: generated,
    declarations,
    map: {
      version: 3,
      file: file.replace(/\.[^.]+$/, '.mjs'),
      sources: [file],
      sourcesContent: [source],
      names: [],
      mappings: mapLines.join(';'),
    },
  };
}
