/** ESM, declaration and source-map generation for one source module. */
import { GnehError, type Metadata, type PassageIR, type Span } from '@gneh/core';
import { offsetToPosition } from '@gneh/source';

function typeFor(p: PassageIR): string {
  const params = Array.isArray(p.metadata.params) ? p.metadata.params : [];
  const types =
    p.metadata.paramTypes && typeof p.metadata.paramTypes === 'object' && !Array.isArray(p.metadata.paramTypes)
      ? (p.metadata.paramTypes as Metadata)
      : {};
  const optional = Array.isArray(p.metadata.optionalParams) ? p.metadata.optionalParams : [];
  return `{ ${params.map((name) => `${JSON.stringify(String(name))}${optional.includes(name) ? '?' : ''}: ${typeof types[String(name)] === 'string' ? types[String(name)] : 'unknown'}`).join('; ')} }`;
}

const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

function vlq(value: number): string {
  let x = value < 0 ? (-value << 1) | 1 : value << 1;
  let out = '';
  do {
    let d = x & 31;
    x >>>= 5;
    if (x) d |= 32;
    out += chars[d];
  } while (x);
  return out;
}

export interface ModuleOutput {
  code: string;
  declarations: string;
  map: Record<string, unknown>;
}

function runtimePassage(passage: PassageIR, id: string): string {
  const {
    name: _name,
    dialect: _dialect,
    source: _source,
    span: _span,
    imports: _imports,
    exports: _exports,
    ...runtime
  } = passage;
  return JSON.stringify({ ...runtime, id }, function (key, value) {
    const compilerRecord =
      this &&
      typeof this === 'object' &&
      ('ast' in this || 'phase' in this || ('type' in this && typeof this.type === 'string'));
    if (key === 'source' && compilerRecord) return undefined;
    if (key === 'span' && compilerRecord && value && typeof value === 'object') return { start: value.start };
    return value;
  });
}

/** A file is one ESM namespace; passage ids live in the typed `fragments` export. */
export function generateModule(
  passages: PassageIR[],
  source = '',
  file = 'story.inkdown',
  options: {
    namespace?: string;
  } = {},
): ModuleOutput {
  if (!passages.length) throw new GnehError('MODULE_EMPTY', 'No passages to compile.');
  const imports = passages
    .flatMap((passage) => passage.imports)
    .filter(
      (value, index, all) =>
        all.findIndex(
          (candidate) =>
            candidate.source === value.source &&
            candidate.imported === value.imported &&
            candidate.local === value.local,
        ) === index,
    );
  const importNames = imports.map((value) => value.local);
  if (
    importNames.some((x) => ['fragments', 'metadata', '__gneh', '__bindings'].includes(x) || /^__(?:ir|f)\d+$/.test(x))
  )
    throw new GnehError('MODULE_RESERVED', 'fragments and metadata are compiler-owned export names.');
  const code: string[] = [
    '// Generated by gneh 0.1.0. Source dialect does not affect the Fragment ABI.',
    'import { defineIRFragment as __gneh } from "@gneh/runtime";',
    ...imports.map(
      (value) =>
        `import { ${value.imported}${value.imported === value.local ? '' : ` as ${value.local}`} } from ${JSON.stringify(value.source)};`,
    ),
  ];
  const mapping: {
    line: number;
    span: Span;
  }[] = [];
  if (importNames.some((name) => passages.some((p) => p.id === name)))
    throw new GnehError(
      'MODULE_SHADOW',
      'A local passage id cannot shadow an ESM binding. Rename the import alias or passage id.',
    );
  const bindings = '__bindings';
  code.push(
    `const __bindings = {${importNames.map((name) => `get ${JSON.stringify(name)}(){ return ${name}; }`).join(',')}};`,
  );
  for (let i = 0; i < passages.length; i++) {
    const p = passages[i];
    code.push(`const __ir${i} = ${runtimePassage(p, options.namespace ? options.namespace + '#' + p.id : p.id)};`);
    mapping.push({ line: code.join('\n').split('\n').length, span: p.span });
    code.push(`const __f${i} = __gneh(__ir${i}, {bindings:${bindings}});`);
  }
  code.push(
    `export const fragments = Object.freeze({${passages.map((p, i) => `${JSON.stringify(p.id)}:__f${i}`).join(',')}});`,
  );
  code.push('Object.assign(__bindings, fragments);');
  const exported = [...new Set(passages.flatMap((passage) => passage.exports))];
  for (const name of exported)
    if (!importNames.includes(name))
      throw new GnehError('EXPORT_UNKNOWN', `@export can only expose an imported binding; ${name} is not imported.`);
  if (exported.length) code.push(`export { ${exported.join(', ')} };`);
  code.push(
    'export const metadata = Object.freeze(Object.fromEntries(Object.entries(fragments).map(([id, fragment]) => [id, fragment.metadata])));',
  );
  code.push('export default __f0;');
  const generated = code.join('\n') + '\n';
  const mapLines = generated.split('\n').map(() => '');
  let previousLine = 0,
    previousColumn = 0;
  for (const m of mapping) {
    const pos = offsetToPosition(source, m.span.start);
    mapLines[m.line] = vlq(0) + vlq(0) + vlq(pos.line - previousLine) + vlq(pos.character - previousColumn);
    previousLine = pos.line;
    previousColumn = pos.character;
  }
  const declarations =
    [
      'import type { Fragment, Metadata } from "@gneh/core";',
      ...exported.map((name) => `export declare const ${name}: unknown;`),
      `export declare const fragments: {${passages.map((p) => `readonly ${JSON.stringify(p.id)}: Fragment<${typeFor(p)}>`).join(';')}};`,
      'export declare const metadata: Readonly<Record<string,Metadata>>;',
      `declare const primary: Fragment<${typeFor(passages[0])}>;`,
      'export default primary;',
    ].join('\n') + '\n';
  return {
    code: generated,
    declarations,
    map: {
      version: 3,
      file: file.replace(/\.[^.]+$/, '.mjs'),
      sources: [file],
      sourcesContent: [source],
      names: [],
      mappings: mapLines.join(';'),
    },
  };
}
